name: docusaurus_update
on:
  push:
    branches:
    - main

env:
  first_env_var: test  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update and restart remote docusaurus
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/services-stakecraft-com
            git pull
            /usr/bin/npx docusaurus download-remote-snapshots && npm run build
            sleep 5
            echo "Restarting node server"
            sudo systemctl restart docusaurus.service
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}
          args: '-o "StrictHostKeyChecking no"'
