name: test
on:
  push:
    branches:
    - main

env:
  FIRST_NAME: Mona
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update remote docusaurus
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/services-stakecraft-com
            git pull
            /usr/bin/npx docusaurus download-remote-snapshots && npm run build
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY}}
          args: '-o "StrictHostKeyChecking no"'
